#!/usr/bin/env bash
# Runs the full Go test suite and appends a structured entry to
# TESTRESULTS.md so we have a per-run protocol committed in git.
#
# Usage: ./scripts/test-report.sh
#        make test-report

set -euo pipefail

cd "$(dirname "$0")/.."

REPORT="TESTRESULTS.md"
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "no-git")
DIRTY=""
if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
    DIRTY=" (dirty)"
fi

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

COVERPROFILE="$TMP/coverage.out"
TESTOUT="$TMP/tests.out"

# Run tests with verbose output and a single coverage profile so we can
# extract per-package percentages afterwards.
go test ./... -v -count=1 -coverprofile="$COVERPROFILE" -covermode=atomic \
    > "$TESTOUT" 2>&1 && STATUS="PASS" || STATUS="FAIL"

# Parse pass/fail/skip counts from the verbose output.
PASS=$(grep -cE '^--- PASS:' "$TESTOUT" || true)
FAIL=$(grep -cE '^--- FAIL:' "$TESTOUT" || true)
SKIP=$(grep -cE '^--- SKIP:' "$TESTOUT" || true)

# Total coverage across all packages that produced any.
TOTAL_COV=""
if [ -s "$COVERPROFILE" ]; then
    TOTAL_COV=$(go tool cover -func="$COVERPROFILE" 2>/dev/null | tail -1 | awk '{print $3}')
fi

# Per-package "ok ..." or "FAIL ..." summary lines from `go test`.
PKG_SUMMARY=$(grep -E '^(ok|FAIL|---|\?)\s+github.com/' "$TESTOUT" \
    | grep -vE '^---' \
    | sed 's|github.com/mattlab76/ccsm-go/||' \
    | head -40)

# Failing tests, if any (test name + immediate context).
FAILED_TESTS=""
if [ "$FAIL" -gt 0 ]; then
    FAILED_TESTS=$(grep -E '^--- FAIL:' "$TESTOUT" | sed 's/^--- /  - /')
fi

# Create the file with a header if it doesn't exist yet.
if [ ! -f "$REPORT" ]; then
    cat > "$REPORT" <<EOF
# Test Run Log

Generated by \`make test-report\` (\`scripts/test-report.sh\`). Newest
entries first. Each entry captures the state of the test suite at one
commit so regressions are visible in git history.

EOF
fi

# Build the new entry in memory, then prepend (newest first).
ENTRY=$(cat <<EOF

## $TIMESTAMP · \`$GIT_SHA\`$DIRTY · $STATUS

- ✓ $PASS passed · ✗ $FAIL failed · ⊘ $SKIP skipped
- Coverage: ${TOTAL_COV:-n/a}

\`\`\`
$PKG_SUMMARY
\`\`\`
EOF
)

if [ -n "$FAILED_TESTS" ]; then
    ENTRY="$ENTRY
Failed tests:
\`\`\`
$FAILED_TESTS
\`\`\`"
fi

# Prepend the new entry after the header (after the first blank line
# following the introductory paragraph).
HEAD=$(awk 'BEGIN{n=0} {print; if (/^$/) n++; if (n==2) exit}' "$REPORT")
TAIL=$(awk 'BEGIN{n=0; on=0} {if (on) print; if (/^$/){n++; if (n==2){on=1}}}' "$REPORT")
{
    printf '%s\n' "$HEAD"
    printf '%s\n' "$ENTRY"
    printf '%s\n' "$TAIL"
} > "$REPORT.new"
mv "$REPORT.new" "$REPORT"

echo
echo "==> $REPORT updated ($STATUS · $PASS passed · $FAIL failed · cov ${TOTAL_COV:-n/a})"

# Stage the report so the user can commit alongside their changes.
git add "$REPORT" 2>/dev/null || true

# Surface failures via exit status so CI / Make halts on red.
[ "$STATUS" = "PASS" ]
